FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/migrate ./cmd/migrate
COPY migrations ./migrations
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags='-s -w' -o /out/gp-migrate ./cmd/migrate

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/gp-migrate /usr/local/bin/gp-migrate
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/gp-migrate"]
