namespaceOverride: gp

imagePullSecrets: []

securityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

secrets:
  existingSecret: ""

migration:
  enabled: false
  image:
    repository: ghcr.io/openware-io/open-green-pass-migrate
    tag: ""
    pullPolicy: IfNotPresent
  env: {}
  resources: {}

server:
  enabled: false
  image:
    repository: ghcr.io/openware-io/open-green-pass
    tag: ""
    pullPolicy: IfNotPresent
  replicas: 1
  env: {}
  resources: {}

worker:
  enabled: false
  image:
    repository: ghcr.io/openware-io/open-green-pass-worker
    tag: ""
    pullPolicy: IfNotPresent
  replicas: 1
  env: {}
  resources: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  hosts: []

resources:
  quota:
    enabled: true
    requestsCpu: "8"
    requestsMemory: 16Gi
    limitsCpu: "16"
    limitsMemory: 32Gi
    pods: "50"
    pvc: "40"
  limitRange:
    enabled: true

networkPolicy:
  enabled: true
