{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gp-server-api
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "gp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gp-server
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gp-web
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "gp.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ if $.Values.web.enabled }}gp-web{{ else }}gp-server{{ end }}
                port:
                  number: {{ if $.Values.web.enabled }}8080{{ else }}{{ $.Values.service.port }}{{ end }}
    {{- end }}
{{- end }}
