{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gp-server
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "gp.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gp-server
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
