{{- $serviceAccount := .Values.serviceAccount | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "gp-controller" (get $serviceAccount "name") }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    {{- include "gp.labels" . | nindent 4 }}
automountServiceAccountToken: true
