/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪检查 */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 构建和 API 版本 */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录会话的团队概览 */
        get: operations["currentTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 微信登录公开配置状态 */
        get: operations["wechatAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/auth/wechat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取微信登录配置 */
        get: operations["getWechatAuthConfig"];
        /** 保存微信登录配置 */
        put: operations["saveWechatAuthConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/wechat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前账号微信绑定状态 */
        get: operations["getWechatBinding"];
        put?: never;
        post?: never;
        /** 解绑当前账号微信 */
        delete: operations["unbindWechat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前团队成员 */
        get: operations["listTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/current/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改当前团队成员角色或状态 */
        patch: operations["updateTeamMember"];
        trace?: never;
    };
    "/teams/current/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前团队被测对象 */
        get: operations["listTeamAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/current/assets/{targetId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 被测对象的成员授权 */
        get: operations["listAssetPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/current/assets/{targetId}/permissions/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 设置成员的被测对象权限及配额 */
        put: operations["updateAssetPermission"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 被测对象树（工程/服务组/服务/模块） */
        get: operations["listTargets"];
        put?: never;
        /** 创建被测对象节点 */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/repo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关联上游仓库（来源溯源） */
        post: operations["attachRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目仓库 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 项目仓库 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRepository"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/repositories:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量添加项目仓库 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        repositories: components["schemas"]["ProjectRepositoryInput"][];
                    };
                };
            };
            responses: {
                /** @description 逐条处理结果 */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchResultResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目目录子服务 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 子服务 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectService"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/services:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按仓库目录批量创建子服务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        services: components["schemas"]["ProjectServiceInput"][];
                    };
                };
            };
            responses: {
                /** @description 逐条处理结果 */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchResultResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/services/{serviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改目录子服务类型 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    serviceId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "api_service" | "gateway" | "websocket_service" | "web_app" | "mobile_app" | "desktop_app" | "other";
                    };
                };
            };
            responses: {
                /** @description 已修改 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/targets/{id}/model-binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询被测对象模型绑定 */
        get: operations["getModelBinding"];
        /** 设置被测对象模型绑定 */
        put: operations["setModelBinding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询可接入模型目录与团队已配置模型 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 模型目录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelCatalog"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 验证并保存团队模型连接 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModelConnectionInput"];
                };
            };
            responses: {
                /** @description 已验证并保存 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description 供应商连接失败 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用例列表 */
        get: operations["listCases"];
        put?: never;
        /** 创建用例（版本化首版） */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 迭代创建用例新版本 */
        post: operations["createCaseVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用例按版本回退（避免错误分支生成） */
        post: operations["rollbackCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用例版本历史对比 */
        get: operations["caseHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用例 */
        delete: operations["deleteCase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/env/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登记测试环境运行版本（env_runtime） */
        post: operations["registerRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/version-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起版本校验（match/mismatch/unknown） */
        post: operations["checkVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/version-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 最近版本校验记录 */
        get: operations["recentChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 测试运行列表 */
        get: operations["listRuns"];
        put?: never;
        /** 创建测试运行（勾选用例空=全量） */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行详情（状态机） */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行状态 SSE 事件流 */
        get: operations["runEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/case-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行内用例结果 */
        get: operations["runCaseResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/version-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发版本校验阶段 */
        post: operations["startVersionCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行运行（重跑 attempt 递增） */
        post: operations["executeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 暂停 */
        post: operations["pauseRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复 */
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 装载门禁策略（版本化，策略即代码） */
        put: operations["upsertGateRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 门禁判定（pass/fail/blocked，入审计链） */
        post: operations["evaluateGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行的门禁判定结果 */
        get: operations["gateResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 成本计量写入（幂等：request_id+biz_point 不双计） */
        post: operations["recordCost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 成本总览（=Σ明细，按大类 generate/execute） */
        get: operations["costOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 成本明细（按大类/细类筛选） */
        get: operations["costItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/compare/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单用例成本历史对比（存量持平/递减证明） */
        get: operations["costCompare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 由运行生成测试报告 */
        post: operations["generateReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 跨场景合编报告（HTML/Markdown） */
        post: operations["bundleReports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/bundle/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导出跨场景合编报告 */
        post: operations["exportBundleReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出报告 */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WechatAuthConfig: {
            /** Format: int64 */
            team_id: number;
            enabled: boolean;
            app_id: string;
            callback_uri: string;
            secret_configured: boolean;
            /** Format: date-time */
            updated_at?: string;
        };
        WechatAuthConfigInput: {
            enabled: boolean;
            app_id: string;
            app_secret?: string;
            callback_uri: string;
        };
        WechatBinding: {
            bound: boolean;
            display_name?: string;
            avatar_url?: string;
        };
        TeamSummary: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            member_count: number;
            /** Format: int64 */
            project_count: number;
        };
        TeamMember: {
            /** Format: int64 */
            id: number;
            principal_id: string;
            username: string;
            display_name: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "tester" | "viewer";
            /** @enum {string} */
            status: "active" | "disabled" | "invited";
            /** Format: date-time */
            last_active_at?: string;
        };
        TeamMemberUpdate: {
            /** @enum {string} */
            role: "owner" | "admin" | "tester" | "viewer";
            /** @enum {string} */
            status: "active" | "disabled" | "invited";
        };
        TeamAsset: {
            /** Format: int64 */
            id: number;
            name: string;
            kind: string;
            /** Format: int64 */
            owner_id?: number;
            owner_name: string;
        };
        AssetGrant: {
            /** Format: int64 */
            member_id: number;
            display_name: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "tester" | "viewer";
            /** @enum {string} */
            permission: "full" | "edit" | "exec" | "view" | "none";
            /** Format: int64 */
            concurrent_quota: number;
            /** Format: int64 */
            sandbox_quota: number;
            /** Format: int64 */
            version: number;
        };
        AssetGrantUpdate: {
            /** @enum {string} */
            permission: "full" | "edit" | "exec" | "view" | "none";
            /** Format: int64 */
            concurrent_quota: number;
            /** Format: int64 */
            sandbox_quota: number;
        };
        ModelPreset: {
            Provider: string;
            Name: string;
            ModelKey: string;
            /** @enum {string} */
            Protocol: "api" | "cc";
            BaseURL: string;
            Capabilities: string[];
        };
        ConfiguredModel: {
            /** Format: int64 */
            id: number;
            provider: string;
            model_key: string;
            status: string;
        };
        ModelCatalog: {
            presets: components["schemas"]["ModelPreset"][];
            models: components["schemas"]["ConfiguredModel"][];
        };
        ModelConnectionInput: {
            provider: string;
            /** @enum {string} */
            protocol: "api" | "cc";
            token: string;
            base_url?: string;
            model_keys: string[];
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            checks: {
                [key: string]: string;
            };
        };
        VersionResponse: {
            version: string;
            commit: string;
            built_at: string;
            api_version: string;
        };
        StatusResponse: {
            status: string;
        };
        Target: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            type: string;
            name: string;
            remark?: string;
            kind: string;
            status: string;
            /** Format: int64 */
            parent_id?: number | null;
            model_binding?: components["schemas"]["ModelBinding"];
        };
        ProjectRepository: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            url: string;
            default_branch: string;
        };
        ProjectRepositoryInput: {
            url: string;
            /** @default main */
            default_branch: string;
        };
        ProjectService: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            project_id: number;
            /** Format: int64 */
            repo_id: number;
            name: string;
            source_path: string;
            /** @enum {string} */
            kind: "api_service" | "gateway" | "websocket_service" | "web_app" | "mobile_app" | "desktop_app" | "other";
            build_context: string;
            dockerfile_path?: string | null;
            manifest_path?: string | null;
            status: string;
        };
        ProjectServiceInput: {
            /** Format: int64 */
            repo_id: number;
            name: string;
            source_path: string;
            /** @enum {string} */
            kind?: "api_service" | "gateway" | "websocket_service" | "web_app" | "mobile_app" | "desktop_app" | "other";
            build_context?: string;
            dockerfile_path?: string | null;
            manifest_path?: string | null;
        };
        BatchResultResponse: {
            results: {
                index: number;
                /** Format: int64 */
                id?: number;
                error?: string;
            }[];
        };
        ModelBinding: {
            model: string;
            provider: string;
            params?: {
                [key: string]: string;
            };
        };
        TestCase: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            code: string;
            title: string;
            kind: string;
            current_version: number;
            status: string;
        };
        CaseVersion: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            case_id: number;
            version: number;
            change_type: string;
            /** Format: int64 */
            source_repo_id?: number | null;
            source_branch?: string | null;
            /** @description 用例脚本/数据 */
            script?: unknown;
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            scenario_id: number;
            /** Format: int64 */
            target_id: number;
            env: string;
            target_version: string;
            target_branch: string;
            env_version: string;
            /** Format: int64 */
            env_check_id?: number | null;
            run_mode: string;
            /** @enum {string} */
            state: "queued" | "version_check" | "scheduled" | "running" | "paused" | "collect" | "gate" | "report" | "done" | "failed";
            selected_cases: number[];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
        };
        CaseResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            case_id: number;
            case_version: number;
            /** @enum {string} */
            status: "pass" | "fail" | "blocked" | "skipped" | "retried";
            result_text: string;
            evidence?: {
                [key: string]: unknown;
            } | null;
            attempt_seq: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            ended_at?: string | null;
        };
        Report: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            target_id: number;
            kind: string;
            title: string;
            version: string;
            branch: string;
            scenario: string;
            status: string;
            summary: {
                [key: string]: unknown;
            };
            evidence?: {
                [key: string]: unknown;
            };
            html: string;
            /** Format: date-time */
            created_at: string;
        };
        ReportBundle: {
            reports: components["schemas"]["Report"][];
            total: number;
            pass: number;
            fail: number;
            html?: string;
            markdown?: string;
        };
        CostOverview: {
            total_amount: number;
            by_category: {
                [key: string]: number;
            };
            by_point: {
                [key: string]: number;
            };
        };
        CostLineItem: {
            /** Format: int64 */
            id: number;
            request_id: string;
            idempotency_key: string;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            case_id: number;
            category: string;
            biz_point: string;
            model: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            unit_price: number;
            amount: number;
            /** Format: date-time */
            occurred_at: string;
        };
        GateResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            rule_id: number;
            /** @enum {string} */
            result: "pass" | "fail" | "blocked";
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            decided_at: string;
        };
        GateRule: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            /** Format: int64 */
            scenario_id: number;
            rego: string;
            version: number;
            enabled: boolean;
        };
        EnvRuntime: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            env: string;
            running_version: string;
            /** Format: date-time */
            checked_at: string;
        };
        EnvCheck: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id?: number | null;
            /** Format: int64 */
            target_id: number;
            target_version: string;
            env_version: string;
            /** @enum {string} */
            result: "match" | "mismatch" | "unknown";
            /** Format: date-time */
            checked_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 依赖可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description 依赖不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    currentTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 团队概览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSummary"];
                };
            };
        };
    };
    wechatAuthStatus: {
        parameters: {
            query: {
                team_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        configured: boolean;
                        enabled: boolean;
                    };
                };
            };
        };
    };
    getWechatAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WechatAuthConfig"];
                };
            };
        };
    };
    saveWechatAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechatAuthConfigInput"];
            };
        };
        responses: {
            /** @description 已配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getWechatBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 绑定状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WechatBinding"];
                };
            };
        };
    };
    unbindWechat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解绑 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTeamMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"][];
                };
            };
        };
    };
    updateTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description 不能降级或停用最后一个拥有者 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTeamAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 被测对象列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAsset"][];
                };
            };
        };
    };
    listAssetPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授权列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetGrant"][];
                };
            };
        };
    };
    updateAssetPermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: number;
                memberId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetGrantUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetGrant"];
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header: {
                "x-gp-team-id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 树形列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    remark?: string;
                    /** @enum {string} */
                    type: "project" | "service_group" | "service" | "module";
                    parent_id?: number;
                    kind?: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    attachRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 仓库地址（如 git@github.com:org/repo.git） */
                    url: string;
                    default_branch?: string;
                };
            };
        };
        responses: {
            /** @description 已关联 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getModelBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型绑定（未配置时为 null） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelBinding"] | null;
                };
            };
        };
    };
    setModelBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelBinding"];
            };
        };
        responses: {
            /** @description 已设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    listCases: {
        parameters: {
            query?: {
                target_id?: number;
                kind?: string;
                code?: string;
                status?: string;
            };
            header: {
                "x-gp-team-id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用例列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"][];
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    code: string;
                    title: string;
                    kind?: string;
                    /** @description 用例脚本/数据（执行产物来源） */
                    script?: unknown;
                };
            };
        };
        responses: {
            /** @description 已创建（含版本） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
        };
    };
    createCaseVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用例脚本/数据 */
                    script: unknown;
                    source_repo_id?: number;
                    source_branch?: string;
                };
            };
        };
        responses: {
            /** @description 新版本已创建 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
        };
    };
    rollbackCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: number;
                };
            };
        };
        responses: {
            /** @description 已回退 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    caseHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本历史 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseVersion"][];
                };
            };
        };
    };
    deleteCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    registerRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    env: string;
                    version: string;
                };
            };
        };
        responses: {
            /** @description 已登记 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvRuntime"];
                };
            };
        };
    };
    checkVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    env: string;
                    target_version: string;
                };
            };
        };
        responses: {
            /** @description 校验结果（mismatch 阻断信号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvCheck"];
                };
            };
        };
    };
    recentChecks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvCheck"][];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                target_id?: number;
                state?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    scenario_id: number;
                    env?: string;
                    target_version: string;
                    target_branch?: string;
                    /** @description 空=全量 */
                    selected_case_ids?: number[];
                };
            };
        };
        responses: {
            /** @description 已创建（queued） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行聚合 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    runEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行状态事件流；每条 data 为 Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    runCaseResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用例结果列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResult"][];
                };
            };
        };
    };
    startVersionCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description mismatch 阻断 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    executeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已启动 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                        results: components["schemas"]["CaseResult"][];
                    };
                };
            };
        };
    };
    pauseRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已暂停 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已恢复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    upsertGateRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    scenario_id: number;
                    /** @description 声明式策略 JSON 或 Rego */
                    rego: string;
                };
            };
        };
        responses: {
            /** @description 已装载（含新版本号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateRule"];
                };
            };
        };
    };
    evaluateGate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    run_id: number;
                };
            };
        };
        responses: {
            /** @description 判定结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateResult"];
                };
            };
        };
    };
    gateResults: {
        parameters: {
            query: {
                run_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 判定列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateResult"][];
                };
            };
        };
    };
    recordCost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    request_id: string;
                    /** @enum {string} */
                    biz_point: "case_generate" | "case_execute" | "gate_judge" | "analysis";
                    target_id?: number;
                    run_id?: number;
                    case_id?: number;
                    model?: string;
                    tokens_in?: number;
                    tokens_out?: number;
                    /** @description 每千 token 单价 */
                    unit_price?: number;
                };
            };
        };
        responses: {
            /** @description inserted 是否新落账（false=幂等跳过） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        inserted?: boolean;
                    };
                };
            };
        };
    };
    costOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 总览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostOverview"];
                };
            };
        };
    };
    costItems: {
        parameters: {
            query?: {
                category?: "generate" | "execute";
                point?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 明细列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostLineItem"][];
                };
            };
        };
    };
    costCompare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 该用例各次成本时序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostLineItem"][];
                };
            };
        };
    };
    generateReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    run_id: number;
                    /**
                     * @description 默认 service；跨场景合编 P2
                     * @enum {string}
                     */
                    kind?: "project" | "service" | "case";
                };
            };
        };
        responses: {
            /** @description 已生成报告（含 HTML） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    bundleReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    report_ids: number[];
                    /**
                     * @default html
                     * @enum {string}
                     */
                    format?: "html" | "markdown";
                };
            };
        };
        responses: {
            /** @description 合编报告内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportBundle"];
                };
            };
        };
    };
    exportBundleReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    report_ids: number[];
                    /** @enum {string} */
                    format: "pdf" | "docx";
                };
            };
        };
        responses: {
            /** @description 二进制报告文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query?: {
                fmt?: "html";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
}
