/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 被测对象树（工程/服务组/服务/模块） */
        get: operations["listTargets"];
        put?: never;
        /** 创建被测对象节点 */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/repo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关联上游仓库（来源溯源） */
        post: operations["attachRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用例列表 */
        get: operations["listCases"];
        put?: never;
        /** 创建用例（版本化首版） */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 迭代创建用例新版本 */
        post: operations["createCaseVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用例按版本回退（避免错误分支生成） */
        post: operations["rollbackCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用例版本历史对比 */
        get: operations["caseHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用例 */
        delete: operations["deleteCase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/env/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登记测试环境运行版本（env_runtime） */
        post: operations["registerRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/version-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起版本校验（match/mismatch/unknown） */
        post: operations["checkVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{id}/version-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 最近版本校验记录 */
        get: operations["recentChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 测试运行列表 */
        get: operations["listRuns"];
        put?: never;
        /** 创建测试运行（勾选用例空=全量） */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行详情（状态机） */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行状态 SSE 事件流 */
        get: operations["runEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/case-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行内用例结果 */
        get: operations["runCaseResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/version-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发版本校验阶段 */
        post: operations["startVersionCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行运行（重跑 attempt 递增） */
        post: operations["executeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 暂停 */
        post: operations["pauseRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复 */
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 装载门禁策略（版本化，策略即代码） */
        put: operations["upsertGateRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 门禁判定（pass/fail/blocked，入审计链） */
        post: operations["evaluateGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行的门禁判定结果 */
        get: operations["gateResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 成本计量写入（幂等：request_id+biz_point 不双计） */
        post: operations["recordCost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 成本总览（=Σ明细，按大类 generate/execute） */
        get: operations["costOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 成本明细（按大类/细类筛选） */
        get: operations["costItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost/compare/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单用例成本历史对比（存量持平/递减证明） */
        get: operations["costCompare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 由运行生成测试报告 */
        post: operations["generateReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 跨场景合编报告（HTML/Markdown） */
        post: operations["bundleReports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出报告 */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            status: string;
        };
        Target: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            type: string;
            name: string;
            kind: string;
            status: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int64 */
            repo_id?: number | null;
        };
        TestCase: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            code: string;
            title: string;
            kind: string;
            current_version: number;
            status: string;
        };
        CaseVersion: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            case_id: number;
            version: number;
            change_type: string;
            /** Format: int64 */
            source_repo_id?: number | null;
            source_branch?: string | null;
            /** @description 用例脚本/数据 */
            script?: unknown;
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
        };
        Run: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            scenario_id: number;
            /** Format: int64 */
            target_id: number;
            env: string;
            target_version: string;
            target_branch: string;
            env_version: string;
            /** Format: int64 */
            env_check_id?: number | null;
            run_mode: string;
            /** @enum {string} */
            state: "queued" | "version_check" | "scheduled" | "running" | "paused" | "collect" | "gate" | "report" | "done" | "failed";
            selected_cases: number[];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
        };
        CaseResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            case_id: number;
            case_version: number;
            /** @enum {string} */
            status: "pass" | "fail" | "blocked" | "skipped" | "retried";
            result_text: string;
            evidence?: {
                [key: string]: unknown;
            } | null;
            attempt_seq: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            ended_at?: string | null;
        };
        Report: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            target_id: number;
            kind: string;
            title: string;
            version: string;
            branch: string;
            scenario: string;
            status: string;
            summary: {
                [key: string]: unknown;
            };
            evidence?: {
                [key: string]: unknown;
            };
            html: string;
            /** Format: date-time */
            created_at: string;
        };
        ReportBundle: {
            reports: components["schemas"]["Report"][];
            total: number;
            pass: number;
            fail: number;
            html?: string;
            markdown?: string;
        };
        CostOverview: {
            total_amount: number;
            by_category: {
                [key: string]: number;
            };
            by_point: {
                [key: string]: number;
            };
        };
        CostLineItem: {
            /** Format: int64 */
            id: number;
            request_id: string;
            idempotency_key: string;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            target_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            case_id: number;
            category: string;
            biz_point: string;
            model: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            unit_price: number;
            amount: number;
            /** Format: date-time */
            occurred_at: string;
        };
        GateResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            team_id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            rule_id: number;
            /** @enum {string} */
            result: "pass" | "fail" | "blocked";
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            decided_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header: {
                "x-gp-team-id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 树形列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    type: "project" | "service_group" | "service" | "module";
                    parent_id?: number;
                    kind?: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
        };
    };
    attachRepo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 仓库地址（如 git@github.com:org/repo.git） */
                    url: string;
                    default_branch?: string;
                };
            };
        };
        responses: {
            /** @description 已关联 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listCases: {
        parameters: {
            query?: {
                target_id?: number;
                kind?: string;
                code?: string;
                status?: string;
            };
            header: {
                "x-gp-team-id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用例列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"][];
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    code: string;
                    title: string;
                    kind?: string;
                    /** @description 用例脚本/数据（执行产物来源） */
                    script?: unknown;
                };
            };
        };
        responses: {
            /** @description 已创建（含版本） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
        };
    };
    createCaseVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 用例脚本/数据 */
                    script: unknown;
                    source_repo_id?: number;
                    source_branch?: string;
                };
            };
        };
        responses: {
            /** @description 新版本已创建 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
        };
    };
    rollbackCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: number;
                };
            };
        };
        responses: {
            /** @description 已回退 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    caseHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本历史 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseVersion"][];
                };
            };
        };
    };
    deleteCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    registerRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    env: string;
                    version: string;
                };
            };
        };
        responses: {
            /** @description 已登记 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    checkVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    env: string;
                    target_version: string;
                };
            };
        };
        responses: {
            /** @description 校验结果（mismatch 阻断信号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        result?: "match" | "mismatch" | "unknown";
                    };
                };
            };
        };
    };
    recentChecks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                target_id?: number;
                state?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    scenario_id: number;
                    env?: string;
                    target_version: string;
                    target_branch?: string;
                    /** @description 空=全量 */
                    selected_case_ids?: number[];
                };
            };
        };
        responses: {
            /** @description 已创建（queued） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行聚合 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    runEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行状态事件流；每条 data 为 Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    runCaseResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用例结果列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseResult"][];
                };
            };
        };
    };
    startVersionCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description mismatch 阻断 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    executeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已启动 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                        results: components["schemas"]["CaseResult"][];
                    };
                };
            };
        };
    };
    pauseRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已暂停 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已恢复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    upsertGateRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_id: number;
                    scenario_id: number;
                    /** @description 声明式策略 JSON 或 Rego */
                    rego: string;
                };
            };
        };
        responses: {
            /** @description 已装载（含新版本号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    evaluateGate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    run_id: number;
                };
            };
        };
        responses: {
            /** @description 判定结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        result?: "pass" | "fail" | "blocked";
                    };
                };
            };
        };
    };
    gateResults: {
        parameters: {
            query: {
                run_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 判定列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateResult"][];
                };
            };
        };
    };
    recordCost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    request_id: string;
                    /** @enum {string} */
                    biz_point: "case_generate" | "case_execute" | "gate_judge" | "analysis";
                    target_id?: number;
                    run_id?: number;
                    case_id?: number;
                    model?: string;
                    tokens_in?: number;
                    tokens_out?: number;
                    /** @description 每千 token 单价 */
                    unit_price?: number;
                };
            };
        };
        responses: {
            /** @description inserted 是否新落账（false=幂等跳过） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        inserted?: boolean;
                    };
                };
            };
        };
    };
    costOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 总览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostOverview"];
                };
            };
        };
    };
    costItems: {
        parameters: {
            query?: {
                category?: "generate" | "execute";
                point?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 明细列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostLineItem"][];
                };
            };
        };
    };
    costCompare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 该用例各次成本时序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostLineItem"][];
                };
            };
        };
    };
    generateReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    run_id: number;
                    /**
                     * @description 默认 service；跨场景合编 P2
                     * @enum {string}
                     */
                    kind?: "project" | "service" | "case";
                };
            };
        };
        responses: {
            /** @description 已生成报告（含 HTML） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    bundleReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    report_ids: number[];
                    /**
                     * @default html
                     * @enum {string}
                     */
                    format?: "html" | "markdown";
                };
            };
        };
        responses: {
            /** @description 合编报告内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportBundle"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query?: {
                fmt?: "html";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
}
