import { useEffect, useMemo, useState } from 'react';
import { Building2, Check, Circle, KeyRound, ShieldCheck, UserPlus, Users, X } from 'lucide-react';
import { toast } from 'sonner';
import { createGreenPassClient, type AssetGrant, type TeamAsset, type TeamMember, type TeamSummary } from '@/api/client';
import { ListFilter, PageHeader } from '@/components/shared';
import { cn } from '@/lib/utils';

const api = createGreenPassClient(Number(import.meta.env.VITE_GP_TEAM_ID ?? 1001), undefined, Number(import.meta.env.VITE_GP_USER_ID ?? 42));
const roles: Array<{ role: TeamMember['role']; label: string }> = [{role:'owner',label:'拥有者'},{role:'admin',label:'管理员'},{role:'tester',label:'测试人员'},{role:'viewer',label:'只读成员'}];
const roleClass: Record<TeamMember['role'], string> = {owner:'bg-purple-50 text-purple-700',admin:'bg-blue-50 text-blue-700',tester:'bg-emerald-50 text-emerald-700',viewer:'bg-slate-100 text-slate-600'};
const statusLabel: Record<TeamMember['status'], string> = {active:'已激活',disabled:'已停用',invited:'待接受'};
const permissions: Array<{ value: AssetGrant['permission']; label: string }> = [{value:'full',label:'完整权限'},{value:'edit',label:'编辑'},{value:'exec',label:'执行'},{value:'view',label:'查看'},{value:'none',label:'无权限'}];
const matrix = [['成员与权限管理',1,1,0,0],['工程配置',1,1,0,0],['测试设计与执行',1,1,1,0],['报告与审计查看',1,1,1,1],['团队所有权移交',1,0,0,0]] as const;

export default function TeamPage() {
  const [team,setTeam]=useState<TeamSummary|null>(null), [members,setMembers]=useState<TeamMember[]>([]), [assets,setAssets]=useState<TeamAsset[]>([]), [grants,setGrants]=useState<AssetGrant[]>([]);
  const [activeAsset,setActiveAsset]=useState<number|null>(null), [query,setQuery]=useState(''), [loading,setLoading]=useState(true);
  useEffect(()=>{void Promise.all([api.currentTeam(),api.teamMembers(),api.teamAssets()]).then(([nextTeam,nextMembers,nextAssets])=>{setTeam(nextTeam);setMembers(nextMembers);setAssets(nextAssets);setActiveAsset(nextAssets[0]?.id??null);}).catch((error)=>toast.error('团队数据加载失败',{description:error instanceof Error?error.message:'服务不可用'})).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(activeAsset!==null)void api.assetPermissions(activeAsset).then(setGrants).catch((error)=>toast.error('权限数据加载失败',{description:error instanceof Error?error.message:'服务不可用'}));},[activeAsset]);
  const filtered=useMemo(()=>{const key=query.trim().toLowerCase();return key?members.filter((member)=>`${member.display_name} ${member.email} ${member.username} ${member.role}`.toLowerCase().includes(key)):members;},[members,query]);
  const changeRole=async(member:TeamMember,role:TeamMember['role'])=>{try{await api.updateTeamMember(member.id,{role,status:member.status});setMembers((all)=>all.map((item)=>item.id===member.id?{...item,role}:item));toast.success(`${member.display_name} 的角色已更新`);}catch(error){toast.error('角色更新失败',{description:error instanceof Error?error.message:'请求失败'});}};
  const saveGrant=async(grant:AssetGrant, next:Partial<Pick<AssetGrant,'permission'|'concurrent_quota'|'sandbox_quota'>>)=>{if(activeAsset===null)return;const updated={...grant,...next};try{await api.updateAssetPermission(activeAsset,grant.member_id,{permission:updated.permission,concurrent_quota:updated.concurrent_quota,sandbox_quota:updated.sandbox_quota});setGrants((all)=>all.map((item)=>item.member_id===grant.member_id?updated:item));toast.success(`${grant.display_name} 的资产权限已更新`);}catch(error){toast.error('权限更新失败',{description:error instanceof Error?error.message:'请求失败'});}};
  const selected=assets.find((asset)=>asset.id===activeAsset);

  return <div><PageHeader title="团队与权限" desc="真实团队成员、角色与被测对象权限管理"><button type="button" disabled title="邀请令牌与邮件服务尚未配置" className="inline-flex items-center gap-1.5 rounded-lg bg-slate-100 px-3 py-2 text-xs text-slate-400"><UserPlus className="h-4 w-4"/>邀请成员（待配置）</button></PageHeader>
    {loading?<div className="card rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">正在读取团队权限数据…</div>:<>
      <div className="card mb-5 rounded-2xl bg-gradient-to-br from-slate-900 to-slate-800 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-5"><div><div className="text-lg font-bold">{team?.name}</div><div className="mt-1 text-xs text-slate-300">团队 ID {team?.id} · 当前登录会话的租户数据空间</div></div><div className="flex gap-8 text-center"><div><div className="text-2xl font-bold">{team?.member_count??0}</div><div className="text-[10px] text-slate-400">活跃成员</div></div><div><div className="text-2xl font-bold">{team?.project_count??0}</div><div className="text-[10px] text-slate-400">在管工程</div></div></div></div></div>
      <div className="grid grid-cols-1 gap-5 xl:grid-cols-3"><section className="card overflow-hidden rounded-xl border border-slate-200 bg-white xl:col-span-2"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-slate-700"><Users className="h-4 w-4 text-emerald-500"/>团队成员</h2><ListFilter search={query} onSearch={setQuery}/></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">成员</th><th>角色</th><th>状态</th><th>最近活跃</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((member)=><tr key={member.id}><td className="px-5 py-3"><div className="font-medium text-slate-800">{member.display_name}</div><div className="text-[10px] text-slate-400">{member.email||member.username}</div></td><td><select value={member.role} onChange={(event)=>void changeRole(member,event.target.value as TeamMember['role'])} className={cn('rounded-lg border-0 px-2 py-1 text-[11px]',roleClass[member.role])}>{roles.map((role)=><option key={role.role} value={role.role}>{role.label}</option>)}</select></td><td className="text-slate-600">{statusLabel[member.status]}</td><td className="text-slate-500">{member.last_active_at?new Date(member.last_active_at).toLocaleString():'尚无记录'}</td></tr>)}</tbody></table></div></section>
        <section className="card rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 text-sm font-semibold text-slate-700"><ShieldCheck className="h-4 w-4 text-emerald-500"/>角色权限矩阵</h2><div className="space-y-2">{matrix.map((row)=><div key={row[0]} className="grid grid-cols-[1fr_repeat(4,28px)] items-center rounded-lg bg-slate-50 px-2 py-2 text-[10px]"><span>{row[0]}</span>{row.slice(1).map((allowed,index)=><span key={index} className="text-center">{allowed?<Check className="inline h-3 w-3 text-emerald-500"/>:<X className="inline h-3 w-3 text-slate-300"/>}</span>)}</div>)}</div><div className="mt-3 grid grid-cols-[1fr_repeat(4,28px)] text-[9px] text-slate-400"><span/><span>拥有</span><span>管理</span><span>测试</span><span>只读</span></div></section></div>
      <div className="card mt-5 rounded-xl border border-slate-200 bg-white p-4 text-xs text-slate-500"><Circle className="mr-2 inline h-4 w-4 text-emerald-500"/>本页数据来自当前登录会话，后端通过 PostgreSQL RLS 强制限定团队边界。</div>
      <section className="card mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-slate-700"><KeyRound className="h-4 w-4 text-emerald-500"/>被测对象权限与资源配额</h2><p className="mt-1 text-[11px] text-slate-500">权限及并发、沙箱配额会真实写入 IAM 数据库。</p></div><div className="flex flex-wrap gap-2 border-b border-slate-100 px-5 py-3">{assets.map((asset)=><button key={asset.id} onClick={()=>setActiveAsset(asset.id)} className={cn('rounded-lg border px-3 py-2 text-left text-xs',asset.id===activeAsset?'border-emerald-400 bg-emerald-50 text-emerald-700':'border-slate-200 text-slate-600')}><div className="font-medium">{asset.name}</div><div className="mt-0.5 text-[9px] opacity-70">{asset.kind}{asset.owner_name?` · ${asset.owner_name}`:''}</div></button>)}</div>
        <div className="overflow-x-auto p-5"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-700"><Building2 className="h-4 w-4"/>{selected?.name??'暂无被测对象'}</div><table className="w-full text-xs"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-4 py-3">成员</th><th>团队角色</th><th>资产权限</th><th>并发配额</th><th>沙箱配额</th></tr></thead><tbody className="divide-y divide-slate-100">{grants.map((grant)=><tr key={grant.member_id}><td className="px-4 py-3"><div className="font-medium text-slate-700">{grant.display_name}</div><div className="text-[10px] text-slate-400">{grant.email}</div></td><td><span className={cn('rounded-full px-2 py-1 text-[10px]',roleClass[grant.role])}>{roles.find((role)=>role.role===grant.role)?.label}</span></td><td><select value={grant.permission} onChange={(event)=>void saveGrant(grant,{permission:event.target.value as AssetGrant['permission']})} className="rounded-lg border border-slate-200 px-2 py-1">{permissions.map((permission)=><option key={permission.value} value={permission.value}>{permission.label}</option>)}</select></td><td><input type="number" min={0} value={grant.concurrent_quota} onChange={(event)=>setGrants((all)=>all.map((item)=>item.member_id===grant.member_id?{...item,concurrent_quota:Number(event.target.value)}:item))} onBlur={(event)=>void saveGrant(grant,{concurrent_quota:Number(event.currentTarget.value)})} className="w-20 rounded-lg border border-slate-200 px-2 py-1"/></td><td><input type="number" min={0} value={grant.sandbox_quota} onChange={(event)=>setGrants((all)=>all.map((item)=>item.member_id===grant.member_id?{...item,sandbox_quota:Number(event.target.value)}:item))} onBlur={(event)=>void saveGrant(grant,{sandbox_quota:Number(event.currentTarget.value)})} className="w-20 rounded-lg border border-slate-200 px-2 py-1"/></td></tr>)}</tbody></table>{assets.length===0&&<div className="py-8 text-center text-sm text-slate-400">请先创建被测项目或服务</div>}</div></section>
    </>}</div>;
}
